const $=id=>document.getElementById(id);
const USERS='starsUsersV1'; let currentUser=null;
const topics={Algebra:[['Solve 3x + 7 = 22.','x = 5'],['Expand 4(x + 3).','4x + 12'],['Factorise x² + 5x.','x(x + 5)']],Fractions:[['Simplify 18/24.','3/4'],['Calculate 2/3 + 1/6.','5/6'],['Find 3/5 of 40.','24']],Percentages:[['Find 15% of 200.','30'],['Increase 80 by 25%.','100'],['Decrease 500 by 10%.','450']],Geometry:[['Area of a triangle, b=8 and h=5?','20 cm²'],['Angles on a straight line add to?','180°'],['Circumference when r=7, π=22/7?','44 cm']]};
function users(){try{return JSON.parse(localStorage.getItem(USERS)||'{}')}catch{return{}}}function saveUsers(v){localStorage.setItem(USERS,JSON.stringify(v))}function key(){return 'stars:'+currentUser.toLowerCase()}function get(){try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return{}}}function save(d){localStorage.setItem(key(),JSON.stringify(d))}function ensure(){let d=get();d.tasks||=[];d.notes||=[];d.mistakes||=[];d.flashcards||={};d.practice||={right:0,wrong:0};d.points??=0;d.focus??=0;d.rewards||=[{name:'Buy a game',cost:100},{name:'Special reward',cost:300}];save(d);return d}function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
function login(name){currentUser=name;ensure();$('auth').classList.add('hidden');$('shell').classList.remove('hidden');$('userName').textContent=name;show('dashboard');renderAll()}
$('loginBtn').onclick=()=>{let n=$('loginName').value.trim(),p=$('loginPin').value.trim(),u=users()[n.toLowerCase()];if(!u||u.pin!==hash(p))return $('authMsg').textContent='Username or PIN is incorrect.';login(u.name)};$('signupBtn').onclick=()=>{let n=$('signupName').value.trim(),p=$('signupPin').value.trim();if(n.length<2||!/^\d{4,8}$/.test(p))return $('authMsg').textContent='Use a username and a 4–8 digit PIN.';let u=users();if(u[n.toLowerCase()])return $('authMsg').textContent='That username already exists.';u[n.toLowerCase()]={name:n,pin:hash(p)};saveUsers(u);login(n)};$('logout').onclick=()=>location.reload();
function show(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(innerWidth<850)$('sidebar').classList.remove('open');renderAll()}document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('menu').onclick=()=>$('sidebar').classList.toggle('open');
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function today(){return new Date().toISOString().slice(0,10)}
function renderDashboard(){if(!currentUser)return;let d=ensure(),todayTasks=d.tasks.filter(t=>t.date===today()&&!t.done),next=[...d.tasks].filter(t=>!t.done).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')).slice(0,4);$('dashTasks').innerHTML=next.length?next.map(t=>`<div class="row"><span class="dot"></span><div><b>${esc(t.title)}</b><small>${esc(t.subject)} · ${esc(t.date||'No date')}</small></div></div>`).join(''):'<div class="empty">Nothing urgent. Add a task to your plan.</div>';$('todayCount').textContent=todayTasks.length;$('points').textContent=d.points;$('focusTotal').textContent=d.focus;$('accuracy').textContent=(d.practice.right+d.practice.wrong)?Math.round(d.practice.right/(d.practice.right+d.practice.wrong)*100)+'%':'—';$('welcome').textContent='Good '+(new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening')+', '+currentUser+'.';}
$('addTask').onclick=()=>{let d=ensure(),title=$('taskTitle').value.trim();if(!title)return;d.tasks.push({id:crypto.randomUUID(),title,subject:$('taskSubject').value.trim()||'Study',date:$('taskDate').value||today(),done:false});save(d);$('taskTitle').value='';renderAll()};function renderTasks(){if(!currentUser)return;let d=ensure();$('taskList').innerHTML=d.tasks.length?[...d.tasks].sort((a,b)=>(a.date||'').localeCompare(b.date||'')).map(t=>`<div class="task ${t.done?'done':''}"><button data-done="${t.id}">${t.done?'✓':'○'}</button><div><b>${esc(t.title)}</b><small>${esc(t.subject)} · ${esc(t.date)}</small></div><button data-del="${t.id}">×</button></div>`).join(''):'<div class="empty">No tasks yet.</div>';document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{let d=ensure(),t=d.tasks.find(x=>x.id===b.dataset.done);t.done=!t.done;save(d);renderAll()});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{let d=ensure();d.tasks=d.tasks.filter(x=>x.id!==b.dataset.del);save(d);renderAll()})}
$('saveNote').onclick=()=>{let d=ensure(),title=$('noteTitle').value.trim(),body=$('noteBody').value.trim();if(!title||!body)return;d.notes.unshift({id:crypto.randomUUID(),title,body,date:new Date().toLocaleDateString()});save(d);$('noteTitle').value=$('noteBody').value='';renderNotes()};function renderNotes(){if(!currentUser)return;let d=ensure();$('notes').innerHTML=d.notes.length?d.notes.map(n=>`<article class="note"><small>${esc(n.date)}</small><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p></article>`).join(''):'<div class="empty">Your notes will appear here.</div>'}
let qTopic='Algebra',qi=0;function renderQ(){let q=topics[qTopic][qi%topics[qTopic].length];$('question').textContent=q[0];$('answer').textContent=q[1];$('answer').classList.add('hidden');$('grade').classList.add('hidden')}$('qTopic').onchange=e=>{qTopic=e.target.value;qi=0;renderQ()};$('reveal').onclick=()=>{$('answer').classList.remove('hidden');$('grade').classList.remove('hidden')};function grade(ok){let d=ensure(),q=topics[qTopic][qi%topics[qTopic].length];d.practice[ok?'right':'wrong']++;if(ok)d.points+=2;else d.mistakes.unshift({q:q[0],a:q[1],topic:qTopic});save(d);qi++;renderQ();renderAll()}$('right').onclick=()=>grade(true);$('wrong').onclick=()=>grade(false);
function renderMistakes(){if(!currentUser)return;let d=ensure();$('mistakes').innerHTML=d.mistakes.length?d.mistakes.map(m=>`<div class="listcard"><small>${esc(m.topic)}</small><b>${esc(m.q)}</b><span>${esc(m.a)}</span></div>`).join(''):'<div class="empty">Missed questions will be saved here automatically.</div>'}
$('addCard').onclick=()=>{let d=ensure(),deck=$('cardDeck').value.trim()||'My Deck',f=$('cardFront').value.trim(),b=$('cardBack').value.trim();if(!f||!b)return;d.flashcards[deck]||=[];d.flashcards[deck].push({id:crypto.randomUUID(),front:f,back:b});save(d);$('cardFront').value=$('cardBack').value='';renderCards()};function renderCards(){if(!currentUser)return;let d=ensure(),arr=[];Object.entries(d.flashcards).forEach(([deck,cards])=>cards.forEach(c=>arr.push({...c,deck})));$('cards').innerHTML=arr.length?arr.map(c=>`<div class="flash"><small>${esc(c.deck)}</small><b>${esc(c.front)}</b><span>${esc(c.back)}</span><button data-cardgood="${c.id}">I knew this · +2</button></div>`).join(''):'<div class="empty">Create your first custom flashcard.</div>';document.querySelectorAll('[data-cardgood]').forEach(b=>b.onclick=()=>{let d=ensure();d.points+=2;save(d);renderAll()})}
let secs=25*60,running=false,int=null;function timer(){let m=String(Math.floor(secs/60)).padStart(2,'0'),s=String(secs%60).padStart(2,'0');$('timer').textContent=m+':'+s}$('timerStart').onclick=()=>{running=!running;$('timerStart').textContent=running?'Pause':'Start';clearInterval(int);if(running)int=setInterval(()=>{secs--;if(secs<=0){clearInterval(int);running=false;let d=ensure(),mins=+$('focusLen').value||25;d.focus+=mins;save(d);secs=mins*60;$('timerStart').textContent='Start';renderAll()}timer()},1000)};$('timerReset').onclick=()=>{clearInterval(int);running=false;secs=(+$('focusLen').value||25)*60;$('timerStart').textContent='Start';timer()};$('focusLen').onchange=()=>{$('timerReset').click()};
function renderRewards(){if(!currentUser)return;let d=ensure(),sorted=[...d.rewards].sort((a,b)=>a.cost-b.cost),next=sorted.find(r=>r.cost>d.points)||sorted.at(-1),pct=next?Math.min(100,d.points/next.cost*100):100;$('rewardPoints').textContent=d.points;$('rewardGoal').textContent=next?`${d.points} / ${next.cost} points · ${next.name}`:`${d.points} points`;$('rewardBar').style.width=pct+'%';$('rewardList').innerHTML=d.rewards.map((r,i)=>`<div class="reward"><input data-rname="${i}" value="${esc(r.name)}"><input data-rcost="${i}" type="number" min="1" value="${r.cost}"></div>`).join('');document.querySelectorAll('[data-rname]').forEach(x=>x.onchange=()=>{let d=ensure();d.rewards[+x.dataset.rname].name=x.value;save(d);renderRewards()});document.querySelectorAll('[data-rcost]').forEach(x=>x.onchange=()=>{let d=ensure();d.rewards[+x.dataset.rcost].cost=Math.max(1,+x.value||1);save(d);renderRewards()})}
function renderAll(){renderDashboard();renderTasks();renderNotes();renderMistakes();renderCards();renderRewards()}$('taskDate').value=today();$('qTopic').innerHTML=Object.keys(topics).map(x=>`<option>${x}</option>`).join('');renderQ();timer();
